=== mwgoldsmith/dvbpsi/misc/dr.dtd
<!ELEMENT dr (descriptor*)>

<!ELEMENT descriptor (integer | boolean | insert | array | carray)*>

<!ELEMENT integer EMPTY>

<!ELEMENT boolean EMPTY>

<!ELEMENT array EMPTY>

<!ELEMENT carray EMPTY>

<!ELEMENT insert (begin? | check? | end?)>

<!ELEMENT begin (#PCDATA)>

<!ELEMENT check (#PCDATA)>

<!ATTLIST descriptor name CDATA #REQUIRED>
<!ATTLIST descriptor sname CDATA #REQUIRED>
<!ATTLIST descriptor msuffix CDATA "0">
<!ATTLIST descriptor gen_args CDATA "0">

<!ATTLIST integer name CDATA #REQUIRED>
<!ATTLIST integer bitcount CDATA #REQUIRED>
<!ATTLIST integer default CDATA #REQUIRED>

<!ATTLIST boolean name CDATA #REQUIRED>
<!ATTLIST boolean default CDATA #REQUIRED>

<!ATTLIST array name CDATA #REQUIRED>
<!ATTLIST array len_name CDATA #REQUIRED>
<!ATTLIST array min_size CDATA #REQUIRED>
<!ATTLIST array max_size CDATA #IMPLIED>
<!ATTLIST array type CDATA #IMPLIED>

<!ATTLIST carray name CDATA #REQUIRED>

=== mwgoldsmith/dvbpsi/misc/dr.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE dr SYSTEM "dr.dtd">

<dr>
  <descriptor name="video stream (b_mpeg2 = false)" sname="mpeg_vstream" msuffix="1" >
    <boolean name="b_multiple_frame_rate" default="0" />
    <integer name="i_frame_rate_code" bitcount="4" default="0" />
    <insert>
      <begin>
  s_decoded.b_mpeg2 = false;</begin>
    </insert>
    <boolean name="b_constrained_parameter" default="0" />
    <boolean name="b_still_picture" default="0" />
  </descriptor>

  <descriptor name="video stream (b_mpeg2 = true)" sname="mpeg_vstream" msuffix="2" >
    <boolean name="b_multiple_frame_rate" default="0" />
    <integer name="i_frame_rate_code" bitcount="4" default="0" />
    <insert>
      <begin>
  s_decoded.b_mpeg2 = true;</begin>
    </insert>
    <boolean name="b_constrained_parameter" default="0" />
    <boolean name="b_still_picture" default="0" />
    <integer name="i_profile_level_indication" bitcount="8" default="0" />
    <integer name="i_chroma_format" bitcount="2" default="0" />
    <boolean name="b_frame_rate_extension" default="0" />
  </descriptor>

  <descriptor name="audio stream" sname="mpeg_astream">
    <boolean name="b_free_format" default="0" />
    <integer name="i_id" bitcount="1" default="0" />
    <integer name="i_layer" bitcount="2" default="0" />
  </descriptor>

  <descriptor name="hierarchy" sname="mpeg_hierarchy">
    <integer name="i_h_type" bitcount="4" default="0" />
    <integer name="i_h_layer_index" bitcount="6" default="0" />
    <integer name="i_h_embedded_layer" bitcount="6" default="0" />
    <integer name="i_h_priority" bitcount="6" default="0" />
  </descriptor>

  <descriptor name="registration" sname="mpeg_registration">
    <insert>
      <begin>
  s_decoded.i_additional_length = 0;</begin>
    </insert>
    <integer name="i_format_identifier" bitcount="32" default="0" />
  </descriptor>

  <descriptor name="data stream alignment" sname="mpeg_ds_alignment">
    <integer name="i_alignment_type" bitcount="8" default="0" />
  </descriptor>

  <descriptor name="target background grid" sname="mpeg_target_bg_grid">
    <integer name="i_horizontal_size" bitcount="14" default="0" />
    <integer name="i_vertical_size" bitcount="14" default="0" />
    <integer name="i_pel_aspect_ratio" bitcount="4" default="0" />
  </descriptor>

  <descriptor name="video window" sname="mpeg_vwindow">
    <integer name="i_horizontal_offset" bitcount="14" default="0" />
    <integer name="i_vertical_offset" bitcount="14" default="0" />
    <integer name="i_window_priority" bitcount="4" default="0" />
  </descriptor>

  <descriptor name="conditional access" sname="mpeg_ca">
    <insert>
      <begin>
  s_decoded.i_private_length = 0;</begin>
    </insert>
    <integer name="i_ca_system_id" bitcount="16" default="0" />
    <integer name="i_ca_pid" bitcount="13" default="0" />
    <array name="i_private_data" len_name="i_private_length" min_size="0" />
  </descriptor>

  <descriptor name="ISO 639 language" sname="mpeg_iso639">
    <array name="code" len_name="i_code_count" min_size="1" />
  </descriptor>

  <descriptor name="system clock" sname="mpeg_system_clock">
    <boolean name="b_external_clock_ref" default="0" />
    <integer name="i_clock_accuracy_integer" bitcount="6" default="0" />
    <integer name="i_clock_accuracy_exponent" bitcount="3" default="0" />
  </descriptor>

  <descriptor name="multiplex buffer utilization" sname="mpeg_mx_buff_utilization">
    <boolean name="b_mdv_valid" default="0" />
    <integer name="i_mx_delay_variation" bitcount="15" default="0" />
    <integer name="i_mx_strategy" bitcount="3" default="0" />
  </descriptor>

  <descriptor name="copyright" sname="mpeg_copyright">
    <insert>
      <begin>
  s_decoded.i_additional_length = 0;</begin>
    </insert>
    <integer name="i_copyright_identifier" bitcount="32" default="0" />
    <array name="i_additional_info" len_name="i_additional_length" min_size="0" />
  </descriptor>

  <descriptor name="maximum bitrate" sname="mpeg_max_bitrate">
    <integer name="i_max_bitrate" bitcount="22" default="0" />
  </descriptor>

  <descriptor name="private data indicator" sname="mpeg_private_data">
    <integer name="i_private_data" bitcount="32" default="0" />
  </descriptor>

  <descriptor name="smoothing buffer" sname="mpeg_smoothing_buffer" gen_args="1">
    <integer name="i_sb_leak_rate" bitcount="22" default="0" />
    <integer name="i_sb_size" bitcount="22" default="0" />
  </descriptor>

  <descriptor name="STD" sname="mpeg_std" gen_args="1">
    <boolean name="b_leak_valid_flag" default="0" />
  </descriptor>

  <descriptor name="IBP" sname="mpeg_ibp" gen_args="1">
    <boolean name="b_closed_gop_flag" default="0" />
    <boolean name="b_identical_gop_flag" default="0" />
    <integer name="i_max_gop_length" bitcount="14" default="1" />
  </descriptor>

  <descriptor name="MPEG-4 video" sname="mpeg_mpeg4_video" gen_args="1">
    <integer name="i_mpeg4_visual_profile_and_level" bitcount="8" default="0" />
  </descriptor>

  <descriptor name="MPEG-4 audio" sname="mpeg_mpeg4_audio" gen_args="1">
    <integer name="i_mpeg4_audio_profile_and_level" bitcount="8" default="0" />
  </descriptor>

  <descriptor name="IOD" sname="mpeg_iod" gen_args="1">
    <integer name="i_scope_of_iod_label" bitcount="8" default="0"/>
    <integer name="i_iod_label" bitcount="8" default="0"/>
    <integer name="i_initial_object_descriptor" bitcount="8" default="0"/>
  </descriptor>
  
  <descriptor name="SL" sname="mpeg_sl" gen_args="1">
    <integer name="i_es_id" bitcount="16" default="0"/>
  </descriptor>

  <descriptor name="FMC" sname="mpeg_fmc" gen_args="1">
    <array name="p_fmc" len_name="i_num_fmc" min_size="1" type="dvbpsi_fmc_t"/>
  </descriptor>

  <descriptor name="External_ES_ID" sname="mpeg_ext_es_id" gen_args="1">
    <integer name="i_ext_es_id" bitcount="16" default="0"/>
  </descriptor>

  <descriptor name="MultiplexBuffer" sname="mpeg_mux_buf" gen_args="1">
    <integer name="i_mb_buf_size" bitcount="24" default="0"/>
    <integer name="i_tb_leak_rate" bitcount="24" default="0"/>
  </descriptor>

  <descriptor name="network name" sname="dvb_network_name">
    <array name="i_name_byte" len_name="i_name_length" min_size="0" />
  </descriptor>

  <descriptor name="service list" sname="dvb_service_list">
    <array name="i_service" len_name="i_service_count" min_size="1" type="dvbpsi_service_list_service_s" />
  </descriptor>

  <descriptor name="stuffing" sname="dvb_stuffing">
    <array name="i_stuffing_byte" len_name="i_stuffing_length" min_size="0" />
  </descriptor>

  <descriptor name="satellite delivery system" sname="dvb_sat_deliv_sys">
    <integer name="i_frequency" bitcount="32" default="0"/>
    <integer name="i_orbital_position" bitcount="16" default="0"/>
    <integer name="i_west_east_flag" bitcount="1" default="0"/>
    <integer name="i_polarization" bitcount="2" default="0"/>
    <integer name="i_roll_off" bitcount="2" default="0"/>
    <integer name="i_modulation_system" bitcount="1" default="0"/>
    <integer name="i_modulation_type" bitcount="2" default="0"/>
    <integer name="i_symbol_rate" bitcount="28" default="0"/>
    <integer name="i_fec_inner" bitcount="4" default="0"/>
  </descriptor>

  <descriptor name="cable delivery system" sname="dvb_cable_deliv_sys">
    <integer name="i_frequency" bitcount="32" default="0"/>
    <integer name="i_modulation" bitcount="8" default="0"/>
    <integer name="i_symbol_rate" bitcount="28" default="0"/>
    <integer name="i_fec_inner" bitcount="4" default="0"/>
    <integer name="i_fec_outer" bitcount="4" default="0"/>
  </descriptor>

  <descriptor name="bouquet name" sname="dvb_bouquet_name">
    <array name="i_char" len_name="i_name_length" min_size="0" />
  </descriptor>

  <descriptor name="service (i_service_provider_name)" sname="dvb_service" msuffix="1">
    <insert>
      <begin>
  s_decoded.i_service_name_length = 0;</begin>
    </insert>
    <integer name="i_service_type" bitcount="8" default="0" />
    <array name="i_service_provider_name" len_name="i_service_provider_name_length" min_size="0" />
  </descriptor>

  <descriptor name="service (i_service_name)" sname="dvb_service" msuffix="2">
    <insert>
      <begin>
  s_decoded.i_service_provider_name_length = 0;</begin>
    </insert>
    <integer name="i_service_type" bitcount="8" default="0" />
    <array name="i_service_name" len_name="i_service_name_length" min_size="0" />
  </descriptor>

  <descriptor name="service (both names)" sname="dvb_service" msuffix="3">
    <insert>
      <begin>
  s_decoded.i_service_provider_name_length = 0;</begin>
    </insert>
    <integer name="i_service_type" bitcount="8" default="0" />
    <array name="i_service_name" len_name="i_service_name_length" min_size="0" max_size="126" />
    <array name="i_service_provider_name" len_name="i_service_provider_name_length" min_size="0" max_size="126" />
  </descriptor>

  <descriptor name="linkage (information service)" sname="dvb_linkage" msuffix="0">
    <insert>
      <begin>
  s_decoded.i_linkage_type = 1;
      </begin>
    </insert>
    <integer name="i_transport_stream_id" bitcount="16" default="0" />
    <integer name="i_original_network_id" bitcount="16" default="0" />
    <integer name="i_service_id" bitcount="16" default="0" />
    <array name="i_private_data" len_name="i_private_data_length" min_size="0" />
  </descriptor>

  <descriptor name="linkage (mobile handover, no extra data)" sname="dvb_linkage" msuffix="1">
    <insert>
      <begin>
  s_decoded.i_linkage_type = 8;
  s_decoded.i_handover_type = 0;
  s_decoded.i_origin_type = 1;
      </begin>
    </insert>
    <integer name="i_transport_stream_id" bitcount="16" default="0" />
    <integer name="i_original_network_id" bitcount="16" default="0" />
    <integer name="i_service_id" bitcount="16" default="0" />
    <array name="i_private_data" len_name="i_private_data_length" min_size="0" max_size="245" />
  </descriptor>
